This is the start of a journey to obtain excellence in myself and a career. This is the overview of my first week following the path to becoming a software craftsman. Follow the development and knowledge obtained on my journey.

The overview- I began this week with a start-up sprint review/introduction. During this time I obtained more insight into the direction and path I was to take and the expectation required for sucess. I plan on taking this on with full strengh and intenisity, but only as quickly as I can achieve excellence in my knowledge and craft. We reviewed the basics of software processing and the break down in human and system interaction. 

Reading-This week's assignment was to read "The Clean Coder" by Robert C Martin. This is a excellent read that I recomend. In this read the main points that jump out to me are as such:
          -- The imporant of self-confidence, and to have pride in one's work. Not in that your work is better then others, but that of responsibilty, and self-preservavtion. The key to becoming a software profession, is not only that you do great work; but have a understanding of oneself, and your abilites. To communicate with excellence and to work with effective time management. 
          -- Test Driven Development(TDD) This concept is in my mind the superior accomplishment to developement of the outdated "waterfall" technique. Though this has its place and time, TDD offers security in code and ensures that you have an understanding on how to write dynamically and with the ability to change. TDD is the concept of writing simples pass/fail test that will prove your code is functional, and does so in short calculated distances for small amounts of code. This in turns allows you to adjust on the go with what you have written. I believe this is not only a great concept in development, but that of life as well. Testing your knowledge and ability in short turn-arounds,  you have a full understanidng of your work or concepts that you are learning. I will be applyimg this concept of TDD to my work as a software cratfsman and my everyday life.
          -- Communication is key. Saying no, and yes are skills that many professionals have lost. The "go with the flow" technique is prevelant and does not allow for effect communication and expectation. Specifically in the business realm. The importance of complete understanding of ones team, organizations, customer, and client is paramount and this read offers some very sound advise from one of the industries greats.

Mac- This week I purchased my first Mac computer to aid in my endeavors of becoming a software craftsman. Though I am learning the system and unlearing the years of microsoft ingrained in my processing. My Mac Book Pro offers the perfect platform and has the perfect capabilities to lanch myself in my career and I fully intend to use it to its fullest capacity.

Website- This week I created my very first website and juarezdaniel.com. Of course it is published with the classic first text. I plan on creating a profile and site that will eventually showoff myself, and my capabilities. Look forward to updates soon as I create my online presence and hope to provie insight on myself to the world. 

Conclustion- At the end of the beginning of my journey to become a software craftsman, I see that my eyes have been opened into a world that I have much to learn and develope. I am filled with excitement, and am eagerally awaiting to learn all there is to learn. In turn I will pass down the knowledge I learn to my pupel when the time is appropriate. Where it be my first introduction in the becoming a softward craftsman, "The Clean Coder", or my very first website. This is beginnings of my knowledge  developement. My take away is to strive for excellence conscientiously. Just striving for excellence will provide improvement, but excellence in a direction can unlock the means for perfection, in coding and life. I will take this to heart along with TDD as I hope to learn new skills and knowledge on my path of becoming a professional software craftsman. 
